name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          docker build . -f Dockerfile.fedora.multiarch -t qiot-hackfest-sensor-service:aarch64-latest
    - name: Push docker image to Docker Hub
      run: |
          docker login docker.io -u $dockerhub_user -p $dockerhub_password
          docker tag qiot-hackfest-sensor-service:aarch64-latest docker.io/bentaljaard/air-quality-sensor:aarch64-latest
          docker push docker.io/bentaljaard/air-quality-sensor:aarch64-latest
